site_name: Docs
site_url: https://docs.katson.com
site_author: Dmitry Katson
site_description: CentralQ documentation

theme: 
  name: material
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - header.autohide
  language: en
  palette:
    scheme: slate
    primary: black
    accent: blue
  font:
    text: Urbanist
    code: Roboto Mono
  logo: assets/logo.svg
  favicon: assets/favicon.png

extra:
  homepage: https://katson.com
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  generator: false
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/DmitryKatson
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/DmitryKatson
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/DmitryKatson/
    - icon: fontawesome/brands/github
      link: https://github.com/DmitryKatson
    - icon: fontawesome/brands/microsoft
      link: https://mvp.microsoft.com/en-us/PublicProfile/5003099?fullName=Dmitry%20Katson

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - CentralQ Chat:
    - CentralQ Chat Home: centralq-chat/index.md
    - Getting Started: centralq-chat/getting-started.md
    - Pricing : centralq-chat/pricing.md
    - Installation : centralq-chat/installation.md
    - Configuration : centralq-chat/configuration.md
    - Knowledgebase:
      - Introduction: centralq-chat/knowledgebase/index.md
      - Private Data:
        - Overview: centralq-chat/knowledgebase/private-data/index.md
        - Files: centralq-chat/knowledgebase/private-data/add-files.md
        - Webpages: centralq-chat/knowledgebase/private-data/add-webpages.md
        - Page scripting: centralq-chat/knowledgebase/private-data/add-page-scripts.md
        - Statistics: centralq-chat/knowledgebase/private-data/statistics.md
      - Public Data: centralq-chat/knowledgebase/public-data.md
    - Chat: centralq-chat/chat.md
    - Data Insights Agent:
      - Introduction: centralq-chat/data-insights/index.md
      - Getting Started: centralq-chat/data-insights/getting-started.md
      - Key Features: centralq-chat/data-insights/features.md
      - How it Works: centralq-chat/data-insights/how-it-works.md
      - Security: centralq-chat/data-insights/security.md
      - Examples & Use Cases: centralq-chat/data-insights/examples.md
    - Behinds the scenes: centralq-chat/behinds-the-scenes.md
    - Limitations: centralq-chat/limitations.md
    - Architecture: centralq-chat/architecture.md
    - Security: centralq-chat/security.md
    - Telemetry: centralq-chat/telemetry.md
    - FAQ: centralq-chat/faq.md
    - Release Notes: centralq-chat/release-notes.md
    - Whitepaper: centralq-chat/whitepaper.md

copyright: Copyright &copy; Katson.com 2025 All rights Reserved


    
